### ISSUE TITLE
Request for Shared Access to Attack Prompt

### ISSUE THREAD

**Issue by Jihuai-wpy** [thu-coai/JailbreakDefense_GoalPriority#1]
I am requesting shared access to the attack prompt. Thank you for considering my request.

**Comment by nonstopfor** [comment]
Thanks for you interest in our work! We currently plan to release the entire data and related code upon the acceptance of our paper. As most of the attack prompts are from existing works, I think you can collect these attack prompts easily~

**Comment by nonstopfor** [comment]
We have updated the code and data.
